### PR TITLE
Implement isUninitializedObject() in ObjectManagerDecorator

### PR DESCRIPTION
**Pull request by greg0ire**
That method will be part of the ObjectManager interface in 4.0.x.

It was introduced in https://github.com/doctrine/persistence/pull/334

### CODE REVIEW

File: src/Persistence/ObjectManagerDecorator.php [hunk 1]
```diff
@@ -82,6 +82,12 @@ public function initializeObject(object $obj)
         $this->wrapped->initializeObject($obj);
     }
 
+    /** @param mixed $value */
+    public function isUninitializedObject($value): bool
+    {
+        return $this->wrapped->isUninitializedObject($value);
```
Comment (derrabus) [inline src/Persistence/ObjectManagerDecorator.php:110]: What if the wrapped object manager does not implement the method?

Comment (greg0ire) [reply src/Persistence/ObjectManagerDecorator.php:110]: Oh… right… guess I'll retarget this to 4.0.x then :disappointed:

Comment (derrabus) [reply src/Persistence/ObjectManagerDecorator.php:110]: No, 3.4.x is fine, you just need to handle that case.

Comment (greg0ire) [reply src/Persistence/ObjectManagerDecorator.php:110]: Then to answer your original question, there will be an `Error: Call to undefined method WrappedObjectManager::isUninitializedObject()`.  Not sure how to handle it better, unless maybe an exception is considered better than an error.

File: composer.json [hunk 2]
```diff
@@ -30,7 +30,7 @@
         "phpstan/phpstan-strict-rules": "^1.1",
         "doctrine/coding-standard": "^12",
         "doctrine/common": "^3.0",
-        "phpunit/phpunit": "^8.5 || ^9.5",
+        "phpunit/phpunit": "^8.5.38 || ^9.5",
```
Comment (greg0ire) [inline composer.json:33]: old versions of PHPUnit seem to struggle with `@requires` annotation that are included in a single-line comment.

File: src/Persistence/ObjectManagerDecorator.php (hunk 1 above)
Comment (SenseException) [reply src/Persistence/ObjectManagerDecorator.php:110]: I neither have another idea how to handle this. I'd suggest an exception too.

Comment (derrabus) [reply src/Persistence/ObjectManagerDecorator.php:110]: Sounds like a plan.

Comment (greg0ire) [reply src/Persistence/ObjectManagerDecorator.php:110]: Ok, I'll use a BadMethodCallException with a better error message than the error then.

File: src/Persistence/ObjectManagerDecorator.php [hunk 3]
```diff
@@ -82,6 +87,29 @@ public function initializeObject(object $obj)
...
+    /** @param mixed $value */
+    public function isUninitializedObject($value): bool
+    {
+        if (! method_exists($this->wrapped, 'isUninitializedObject')) {
+            $wrappedClass = get_class($this->wrapped);
+
+            throw new BadMethodCallException(sprintf(
+                <<<'EXCEPTION'
+Context: Trying to call %s
+Problem: The wrapped ObjectManager, an instance of %s does not implement this method.
```
Comment (SenseException) [inline src/Persistence/ObjectManagerDecorator.php:99]: `__METHOD__` does also contain the FQCN. You could shorten the "instance of" Exception text if you like.

**Review by SenseException — APPROVED** [review]

File: src/Persistence/ObjectManagerDecorator.php (hunk 3 above)
Comment (greg0ire) [reply src/Persistence/ObjectManagerDecorator.php:99]: Not really, since the FQCN at hand is not the same as the one referred to in the "Problem" part. In the context part, I say we are calling the decorator, in the problem part, I talk about the decorated class.
